---
name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker-fedora:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image for Fedora
        run: docker build -t packagekit-fedora -f contrib/ci/Dockerfile-fedora .
      - name: Build colord in Fedora
        run: docker run -t -v `pwd`:/build packagekit-fedora ./contrib/ci/build_and_test.sh
  docker-debian:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build the Docker image for Debian
        run: docker build -t packagekit-debian -f contrib/ci/Dockerfile-debian .
      - name: Build colord in Debian
        run: docker run -t -v `pwd`:/build packagekit-debian ./contrib/ci/build_and_test.sh
